const eng = {
  translation: {
    success: 'RSS approved!',
    name: 'RSS Aggregator',
    'auto-upt': 'Auto Update',
    'full-text': 'View Full',
    desc: 'Description',
    date: 'Date Published',
    feed: 'Feed',
    lng: 'Language',
    cate: 'Category',
    description: "Start reading RSS today! It's easy and enjoyable.",
    textUrl: 'RSS URL',
    button: 'Add',
    feeds: 'Feeds',
    posts: 'Posts',
    'btn-text': 'More',
    'more-det': 'More Details',
    'less-det': 'Less Details',
    example: 'Example: https://justinpot.com/feed',
    error: {
      loading: 'Sorry, we are having trouble loading this RSS.',
      'not-rss': "Sorry, this URL doesn't have any RSS.",
      unspecific: 'Oops, something went wrong!',
      ValidationError: 'This must be a valid URL.',
      exist: "Sorry, but you can't add the same RSS twice.",
    },
  },
};

const esp = {
  translation: {
    success: '¡RSS aprobado!',
    name: 'Agregador RSS',
    'auto-upt': 'Actualización automática',
    'full-text': 'Ver completo',
    desc: 'Descripción',
    date: 'Fecha de publicación',
    feed: 'Fuente',
    lng: 'Idioma',
    cate: 'Categoría',
    description: '¡Empieza a leer RSS hoy! Es fácil y agradable.',
    textUrl: 'URL del RSS',
    button: 'Agregar',
    feeds: 'Fuentes',
    posts: 'Publicaciones',
    'btn-text': 'Más',
    'more-det': 'Más detalles',
    'less-det': 'Menos detalles',
    example: 'Ejemplo: https://justinpot.com/feed',
    error: {
      loading: 'Lo sentimos, tenemos problemas para cargar este RSS.',
      unspecific: '¡Ups! Algo salió mal.',
      'not-rss': 'Lo sentimos, esta URL no contiene ningún RSS.',
      ValidationError: 'Por favor, ingrese una URL válida.',
      exist: 'Lo sentimos, no puedes agregar dos RSS iguales.',
    },
  },
};

const ger = {
  translation: {
    success: 'RSS genehmigt!',
    name: 'RSS-Aggregator',
    'auto-upt': 'Auto-Update',
    'full-text': 'Vollständig ansehen',
    desc: 'Beschreibung',
    date: 'Veröffentlichungsdatum',
    feed: 'Feed',
    lng: 'Sprache',
    cate: 'Kategorie',
    description: 'Beginne heute mit dem Lesen von RSS! Es ist einfach, es ist angenehm.',
    textUrl: 'RSS-URL',
    button: 'Hinzufügen',
    feeds: 'Feeds',
    posts: 'Beiträge',
    'btn-text': 'Mehr',
    'more-det': 'Mehr Details',
    'less-det': 'Weniger Details',
    example: 'Beispiel: https://justinpot.com/feed',
    error: {
      loading: 'Entschuldigung, wir haben ein Problem beim Laden dieses RSS.',
      'not-rss': 'Entschuldigung, diese URL enthält kein RSS.',
      unspecific: 'Ups, etwas ist schiefgelaufen!',
      ValidationError: 'Dies muss eine gültige URL sein.',
      exist: 'Entschuldigung, aber Sie können nicht zwei identische RSS hinzufügen.',
    },
  },
};

export { eng, esp, ger };
